#!/bin/bash
### BEGIN INIT INFO
# Provides: revsw-rum
# Required-Start: $network $local_fs
# Required-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: revsw-rum service
# Description: Run control script for Rev RUM service
### END INIT INFO


. /lib/lsb/init-functions

export PATH="$PATH:/usr/local/bin"
base_path="/opt/revsw-rum"


if [ -f /etc/default/revsw-rum ]; then
        . /etc/default/revsw-rum
fi

FOREVER=`which forever`

if [ -z "$FOREVER" ]; then
        echo "Error: 'forever' tool cannot be found - aborting"
        exit 1
fi

#Script created by Srikanth Thota
case "$1" in
        start)

                if [ ! -z "`forever list|egrep -e '(server.js)'`" ] ; then
                        log_action_msg "At least one component is already running..." || true
                        exit 1
                fi
                
                log_action_msg "Starting RUM Service..." || true        
                
                cd $base_path/
                forever start --append -o $base_path/log/rum.log server.js

        ;;
        stop)

                log_daemon_msg "Stopping RUM Service..." || true

                cd $base_path/
                forever stop -o $base_path/log/rum.log server.js
                         
        ;;
        restart)
                log_daemon_msg "Restarting RUM Service..." || true
                $0 stop
                $0 start
        ;;
        status)
                forever list
                if [ ! -z "`forever list|egrep -e '(server.js)'`" ] ; then
                        log_action_msg "At least one component is already running..." || true
                        exit 1
                fi
        ;;

        *)
                log_action_msg "Usage: $0 {start|stop|restart|status}" || true
                exit 1
        ;;
esac
